### Hellow word
GET http://127.0.0.1:5000/hello


###Criar pagamento
POST http://127.0.0.1:5000/payments/pix
Content-Type: application/json

{
  "value": 47000
}

###Rota pra gerar o Qr_code
GET http://127.0.0.1:5000/payments/pix/qr_code/qr_code_payment_09f87141-4658-4a29-9f28-4dce3600dd4e



###Pix Confirmation
POST http://127.0.0.1:5000/payments/pix/confirmation
Content-Type: application/json

{
  "bank_paid_id": "7b1f952f-a6f3-4eba-a4c4-115f4c7b5b6b",
  "value": 47000
}